<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>SlnDependencyStudio.Shared</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SlnDependencyDiagramGenerator.Tests.Unit" />
    <InternalsVisibleTo Include="SlnDependencyDiagramGenerator.Tests.Integration" />
    <InternalsVisibleTo Include="SlnDependencyStudio.Shared.Tests.Unit" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AllOverIt.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Serilog.Extensions.Hosting" />
    <PackageReference Include="Serilog.Sinks.RollingFile" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Source\SlnDependencyDiagramGenerator.csproj" />
  </ItemGroup>

</Project>
