<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>SlnDependencyStudio.Shared</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SlnDependencyDiagramGenerator.Tests.Unit" />
    <InternalsVisibleTo Include="SlnDependencyDiagramGenerator.Tests.Integration" />
    <InternalsVisibleTo Include="SlnDependencyStudio.Shared.Tests.Unit" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AllOverIt.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Serilog.Extensions.Hosting" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="System.Reactive" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Source\SlnDependencyDiagramGenerator.csproj" />
  </ItemGroup>

</Project>
