<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>SlnDependencyStudio.Cli</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SlnDependencyStudio.Cli.Tests.Unit" />
    <InternalsVisibleTo Include="SlnDependencyStudio.Cli.Tests.Integration" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
    <PackageReference Include="AllOverIt.GenericHost" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Serilog.Sinks.Console" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Source\SlnDependencyDiagramGenerator.csproj" />
    <ProjectReference Include="..\SlnDependencyStudio.Shared\SlnDependencyStudio.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="OpenTerminal.bat">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="sample.sds">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
