<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows10.0.19041</TargetFramework>
		<UseWPF>true</UseWPF>
		<LangVersion>Latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>SlnDependencyStudio.Wpf</RootNamespace>
		<AssemblyName>SlnDependencyStudio.Wpf</AssemblyName>
		<ApplicationIcon>app.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="SlnDependencyStudio.Wpf.Tests.Unit" />
	</ItemGroup>

	<ItemGroup>
		<Resource Include="app.ico" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="ReactiveUI" />
		<PackageReference Include="ReactiveUI.WPF" />
		<PackageReference Include="MaterialDesignThemes" />
		<PackageReference Include="AllOverIt.ReactiveUI" />
		<PackageReference Include="AllOverIt.ReactiveUI.Wpf" />
		<PackageReference Include="AllOverIt.DependencyInjection" />
		<PackageReference Include="Microsoft.Extensions.Hosting" />
		<PackageReference Include="Serilog.Extensions.Hosting" />
		<PackageReference Include="Serilog.Sinks.RollingFile" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Source\SlnDependencyDiagramGenerator.csproj" />
		<ProjectReference Include="..\SlnDependencyStudio.Shared\SlnDependencyStudio.Shared.csproj" />
	</ItemGroup>

</Project>
