<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AllOverIt.Validation" />
        <PackageReference Include="coverlet.collector" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
        <PackageReference Include="Microsoft.Extensions.Logging" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="NSubstitute" />
        <PackageReference Include="Shouldly" />
        <PackageReference Include="xunit" />
        <PackageReference Include="xunit.runner.visualstudio" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="..\..\Shared\DisposableTempDirectory.cs" Link="Support\DisposableTempDirectory.cs" />
        <Compile Include="..\..\Shared\DisposableTempFile.cs" Link="Support\DisposableTempFile.cs" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\Source\SlnDependencyDiagramGenerator.csproj" />
        <ProjectReference Include="..\..\..\Studio\SlnDependencyStudio.Shared\SlnDependencyStudio.Shared.csproj" />
    </ItemGroup>

</Project>
