<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="AllOverIt" Version="9.3.1" />
    <PackageVersion Include="AllOverIt.Validation" Version="9.3.1" />
    <PackageVersion Include="Microsoft.Build.Locator" Version="1.11.2" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.9" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.8" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.300" />
    <PackageVersion Include="Microsoft.VisualStudio.SolutionPersistence" Version="1.0.52" />
    <PackageVersion Include="NuGet.Frameworks" Version="7.6.0" />
    <PackageVersion Include="NuGet.ProjectModel" Version="7.6.0" />
    <PackageVersion Include="NuGet.Protocol" Version="7.6.0" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net8.0' or '$(TargetFramework)' == 'net9.0' ">
    <PackageVersion Include="Microsoft.Build" Version="17.11.4" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net10.0' ">
    <PackageVersion Include="Microsoft.Build" Version="18.6.3" />
  </ItemGroup>
</Project>
